//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalmedya.NttModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFestegramEntities1 : DbContext
    {
        public DbFestegramEntities1()
            : base("name=DbFestegramEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_geribildirim> tbl_geribildirim { get; set; }
        public virtual DbSet<tbl_gyorum> tbl_gyorum { get; set; }
        public virtual DbSet<tbl_kullanici> tbl_kullanici { get; set; }
        public virtual DbSet<tbl_kullanicigönderi> tbl_kullanicigönderi { get; set; }
        public virtual DbSet<tbl_takip> tbl_takip { get; set; }
    }
}
