//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sosyalmedya.NttModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_takip
    {
        public int id { get; set; }
        public string takipeden { get; set; }
        public string takipedilen { get; set; }
        public Nullable<int> sil_id { get; set; }
    }
}
